context:
  name: tree-sitter-embedded-template
  version: "0.23.2"
  python_min: 3.9

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/tree-sitter/tree-sitter-embedded-template/archive/refs/tags/v${{ version }}.tar.gz
  sha256: eeda286631c6086b6fbe6d2a2c5cc8c1ea6129aaaf5bef4ca4b9a3f44d829569
  # Source missing tree_sitter/parser.h
  # url: https://pypi.org/packages/source/t/tree-sitter-embedded-template/tree_sitter_embedded_template-${{ version }}.tar.gz
  # sha256: 7b24dcf2e92497f54323e617564d36866230a8bfb719dbb7b45b461510dcddaa

build:
  script:
    - ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: target_platform != build_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools >=42
  run:
    - python

tests:
  - python:
      imports:
        - tree_sitter_embedded_template
      pip_check: true
  - script:
      - python -m pytest bindings/python/tests/
    requirements:
      run:
        - pytest
        - python
        - tree_sitter
    files:
      source:
        - bindings/python/tests/

about:
  homepage: https://github.com/tree-sitter/tree-sitter-embedded-template
  summary: 'A tree-sitter parser for templating languages like ERB and EJS.'
  description: |
    A tree-sitter parser for templating languages like ERB and EJS,
    in which scripting code can be embedded within text content using
    the delimiters <% and %>
  license: MIT
  license_file: LICENSE
  repository: https://github.com/tree-sitter/tree-sitter-embedded-template

extra:
  recipe-maintainers:
    - MementoRC
